{% set version = "0.10.2" %}
{% set sha256 = "7cc753ff8c9caa6b938230cda5f66fd0d79b951d8ce044d843b8c516d44b4735" %}

package:
  name: seq-lang
  version: {{ version }}

source:
  url: https://github.com/seq-lang/seq/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - make
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - xorg-libx11
  host:
    - zlib
  run:
    - zlib
test:
  commands:
    - seqtest 

about:
  home: https://github.com/seq-lang/seq
  license: Apache-2.0
  license_file: LICENSE
  summary: A strongly-typed and statically-compiled high-performance Pythonic language!
